### ISSUE TITLE
帝国主义对华资本输出条约

### ISSUE THREAD

**Issue by 7y-7** [SleepySoft/History#1]

**Comment by 7y-7** [comment]
1841年1月下旬耆善与义律签订《穿鼻草约》

**Comment by 7y-7** [comment]
1841年5月27日，奕山与义律签订了《广州和约》。

**Comment by 7y-7** [comment]
1842年8月29日耆英、伊里布与璞鼎查在南京下关江面的英国军舰“皋华丽”号上签订了中英《南京条约》。

**Comment by 7y-7** [comment]
1843年7月22日，英国强迫清政府补订了《五口通商章程》，并在香港公布。

**Comment by 7y-7** [comment]
1843年10月8日，双方又在虎门签订了《五口通商附粘善后条款》，即《虎门条约》。

**Comment by 7y-7** [comment]
1844年7月3日，清政府被迫派耆英与顾盛在澳门附近的望厦村签订了《望厦条约》。

**Comment by 7y-7** [comment]
1844年10月24日，清政府派耆英在广州附近的黄埔与拉萼尼签订了《黄埔条约》。

**Comment by 7y-7** [comment]
1851年8月6日，伊犁将军耆山与沙俄代表签订了中俄《伊犁塔尔巴哈台通商章程》。

**Comment by 7y-7** [comment]
1858年6月13日，俄使普提雅廷施诱逼签订中俄《天津条约》。

**Comment by 7y-7** [comment]
1858年6月18日，美使列卫廉逼签了中美《天津条约》。

**Comment by 7y-7** [comment]
1858年6月26日，中英《天津条约》。

**Comment by 7y-7** [comment]
1858年6月27日，中法《天津条约》。

**Comment by 7y-7** [comment]
1858年11月，桂良在上海又同英法美三国分别签订了《通商章程善后条约》。

**Comment by 7y-7** [comment]
恭亲王于1860年10月24日、25日分别与额尔金、葛罗交换了《天津条约》批准书，并签订了中英、中法《北京条约》。

**Comment by SleepySoft** [comment]
多谢。你可以新建一个文件，并提交一个pull request。

**Comment by 7y-7** [comment]
多谢关闭。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月02日 16:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [SleepySoft/History] 帝国主义对华资本输出条约 (Issue #1) |

Closed #1 as completed.
